name: k_chart
description: A Flutter K Chart.
version: 0.1.1
author: Mafanwei <eraofma@qq.com>
homepage: https://github.com/mafanwei/k_chart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
